# Railway Deployment Configuration
# This file configures deployment on Railway.app

[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8501"
PYTHONUNBUFFERED = "1"
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_SERVER_PORT = "8501"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"

# Add these in Railway dashboard:
# OPENAI_API_KEY = "your-api-key"
# RATE_LIMIT_DOCS_HOUR = "5"
# RATE_LIMIT_DOCS_DAY = "20"
